[package]
name = "tbn_engine"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
bytemuck = { version = "1.23", features = ["derive"] }
cgmath = "0.18" 
env_logger = "0.11"
pollster = "0.4"
wgpu = "25"
winit = "0.30.8" 
